<?php

/**
 * @file
 */

/**
 * Implements hook_permission().
 */
function dru_claim_permission() {
  return [
    'create claim' => [
      'title' => t('Create Claim'),
      'description' => t('Allow users to create claim'),
    ],
  ];
}

/**
 * Implements hook_menu().
 */
function dru_claim_menu() {
  $items['ticket/node/nojs/%node/%'] = [
    'page callback' => 'dru_claim_node',
    'file' => 'dru_claim.pages.inc',
    'page arguments' => [2, 3, 4],
    'access arguments' => ['create claim'],
    'type' => MENU_CALLBACK,
  ];
  $items['ticket/node/ajax/%node/%'] = [
    'page callback' => 'dru_claim_node',
    'file' => 'dru_claim.pages.inc',
    'page arguments' => [2, 3, 4],
    'access arguments' => ['create claim'],
    'delivery callback' => 'ajax_deliver',
    'type' => MENU_CALLBACK,
  ];
  $items['ticket/comment/nojs/%comment/%'] = [
    'page callback' => 'dru_claim_comment',
    'file' => 'dru_claim.pages.inc',
    'page arguments' => [2, 3, 4],
    'access arguments' => ['create claim'],
    'type' => MENU_CALLBACK,
  ];
  $items['ticket/comment/ajax/%comment/%'] = [
    'page callback' => 'dru_claim_comment',
    'file' => 'dru_claim.pages.inc',
    'page arguments' => [2, 3, 4],
    'access arguments' => ['create claim'],
    'delivery callback' => 'ajax_deliver',
    'type' => MENU_CALLBACK,
  ];

  return $items;
}

/**
 * Implements hook_preprocess_node().
 */
function dru_claim_preprocess_node(&$vars) {
  if (!empty($vars['claim'])) {
    $vars['classes_array'][] = 'dru-claim-process node-claim';
  }
}

/**
 * Implements hook_node_view().
 */
function dru_claim_node_view($node, $view_mode) {
  drupal_add_css(drupal_get_path('module', 'dru_claim') . '/dru_claim.css');

  if ($node->type == 'ticket') {
    $claim = db_select('ticket_claim', 't')
      ->fields('t')
      ->condition('t.ticket_id', $node->nid, '=')
      ->execute()
      ->fetchObject();

    if (!empty($claim)) {
      $initiator = user_load($claim->init_uid);
      $node->content['initiator'] = [
        '#markup' => '<div class="initiator">
            <div class="label">' . t('Initiator') . ':</div>
            <div class="value">' . l($initiator->name, 'user/' . $initiator->uid) . '</div>
          </div>',
      ];

      if ($claim->content_type == 'node') {
        $original = node_load($claim->content_id);
        $original_format = $original->body[LANGUAGE_NONE][0]['format'];
        $original_text = $original->body[LANGUAGE_NONE][0]['value'];
        $original_title = l($original->title, 'node/' . $claim->content_id);
      }
      else {
        $original = comment_load($claim->content_id);
        $original_format = $original->comment_body[LANGUAGE_NONE][0]['format'];
        $original_text = $original->comment_body[LANGUAGE_NONE][0]['value'];
        $original_title = l($original->subject, 'comment/' . $claim->content_id, ['fragment' => 'comment-' . $claim->content_id]);
      }

      if ($view_mode == 'full') {
        $node->content['entity'] = [
          '#markup' => '<div class="entity claimed-entity claimed-entity-full">
            <div class="label claim-entity-label">' . t('Entity') . ':</div>
            <div class="value claimed-entity-value">' . $original_title . check_markup($original_text, $original_format) . '</div>
          </div>',
        ];
      }
      else {
        $node->content['entity'] = [
          '#markup' => '<div class="entity claimed-entity claimed-entity-teaser">
            <div class="label claim-entity-label">' . t('Entity') . ':</div>
            <div class="value claimed-entity-value">' . $original_title . '</div>
          </div>',
        ];
      }
    }

  }

  // Add node links.
  if ($node->type != 'ticket' && user_access('create claim')) {
    drupal_add_js(drupal_get_path('module', 'dru_tickets') . '/dru_tickets.js');

    drupal_add_library('system', 'drupal.ajax');
    $token = drupal_get_token('dru_claim');

    if (isset($node->claim) && $node->claim == 0) {
      $node->content['links']['comment']['#links']['dru-claim'] = [
        'title' => t('Claim'),
        'href' => 'ticket/node/nojs/' . $node->nid . '/' . $token,
        'query' => drupal_get_destination(),
        'attributes' => [
          'class' => ['use-ajax', 'claim-node-' . $node->nid],
        ],
      ];
    }
  }

  // View claim verdict.
  if (user_is_logged_in()) {
    if (isset($node->claim) && $node->claim && $ticket = node_load($node->claim)) {
      $node->content += dru_claim_get_ticket_info($ticket, $node, 'node');
    }
  }
}

/**
 * Get body with ticket info.
 */
function dru_claim_get_ticket_info($ticket, $entity, $entity_type) {
  $output = [];

  $verdict = $ticket->ticket->ticket_verdict;
  $icon = $verdict ? 'balance-scale' : 'spinner fa-pulse';
  $class = $verdict ? 'claim_message_done' : 'claim_message_processed';
  $verdict = $verdict ?: t('Claim is under review');

  $ticket_author = user_load($ticket->uid);
  $ticket_category = taxonomy_term_load($ticket->field_claim_category['und'][0]['tid']);

  $ticket_body = '';
  if (!empty($ticket->body['und'][0]['value'])) {
    $ticket_body = '<i class="fa fa-commenting-o"></i>';
    $ticket_body .= $ticket->body['und'][0]['value'];;
  }

  $output['claim'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['claim_message', $class]
    ],
    'icon' => [
      '#type' => 'markup',
      '#markup' => '<i class="fa fa-'. $icon .'"></i>',
      '#prefix' => '<span class="icon-wrapper">',
      '#suffix' => '</span>'
    ],
    'verdict' => [
      '#type' => 'markup',
      '#markup' => $verdict,
    ]
  ];

  $output['ticket'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['ticket-info']
    ]
  ];
  $output['ticket']['body-wrapper'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['ticket-body']
    ],
    'body' => [
      '#type' => 'markup',
      '#markup' => $ticket_body
    ]
  ];
  $output['ticket']['category-wrapper'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['ticket-category']
    ],
    'icon' => [
      '#type' => 'markup',
      '#markup' => '<i class="fa fa-exclamation-triangle"></i>'
    ],
    'category' => [
      '#type' => 'markup',
      '#markup' => $ticket_category->name
    ],
  ];
  $output['ticket']['created-wrapper'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['ticket-created', 'small-inline-text']
    ],
    'icon' => [
      '#type' => 'markup',
      '#markup' => '<i class="fa fa-calendar"></i>'
    ],
    'created' => [
      '#type' => 'markup',
      '#markup' => date('d.m.Y', $ticket->created)
    ],
  ];
  $output['ticket']['id-wrapper'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['ticket-id', 'small-inline-text']
    ],
    'icon' => [
      '#type' => 'markup',
      '#markup' => '<i class="fa fa-eye"></i>'
    ],
    'id' => [
      '#type' => 'markup',
      '#markup' => l(t('Open ticket'), 'node/' . $ticket->nid)
    ],
  ];
  $output['ticket']['author-wrapper'] = [
    '#type' => 'container',
    '#attributes' => [
      'class' => ['ticket-author', 'small-inline-text']
    ],
    'icon' => [
      '#type' => 'markup',
      '#markup' => '<i class="fa fa-user"></i>'
    ],
    'author' => [
      '#type' => 'markup',
      '#markup' => l($ticket_author->name, 'user/' . $ticket_author->uid)
    ],
  ];

  return $output;
}

/**
 * Implements hook_preprocess_field().
 */
function dru_claim_preprocess_field(&$vars) {
  if ($vars['element']['#field_name'] == 'body' && $vars['element']['#entity_type'] == 'node') {
    $vars['classes_array'][] = 'body-' . $vars['element']['#object']->nid;
  }
  if ($vars['element']['#field_name'] == 'comment_body' && $vars['element']['#entity_type'] == 'comment') {
    $vars['classes_array'][] = 'body-' . $vars['element']['#object']->cid;
  }
}

/**
 * Implements hook_preprocess_comment().
 */
function dru_claim_preprocess_comment(&$vars) {
  if ($vars['comment']->claim <> 0) {
    $vars['classes_array'][] = 'dru-claim comment-claim';
  }
}

/**
 * Implements hook_comment_view().
 */
function dru_claim_comment_view($comment, $view_mode) {
  // Add comment links.
  drupal_add_css(drupal_get_path('module', 'dru_claim') . '/dru_claim.css');
  if (user_access('create claim')) {
    drupal_add_js(drupal_get_path('module', 'dru_tickets') . '/dru_tickets.js');
    drupal_add_library('system', 'drupal.ajax');
    $token = drupal_get_token('dru_claim');

    if ($comment->claim == 0 && $comment->node_type != 'comment_node_ticket') {
      $comment->content['links']['comment']['#links']['dru-claim'] = [
        'title' => t('Claim'),
        'href' => 'ticket/comment/nojs/' . $comment->cid . '/' . $token,
        'query' => drupal_get_destination(),
        'attributes' => [
          'class' => ['use-ajax', 'claim-comment-' . $comment->cid],
        ],
      ];
    }
  }

  // View claim verdict.
  if (user_is_logged_in()) {
    if ($comment->claim <> 0) {
      $ticket = node_load($comment->claim);
      $comment->content += dru_claim_get_ticket_info($ticket, $comment, 'comment');
    }
  }
}
