<?php

/**
 * @file
 */

/**
 * Implements hook_comment_view().
 */
function dru_comment_quote_comment_view($comment) {
  if (user_access('post comments')) {
    $node = node_load($comment->nid);
    if ($node->comment == COMMENT_NODE_OPEN) {
      $comment->content['#pre_render'][] = 'dru_comment_quote_link_pre_render';
    }
  }
}

/**
 * Implements hook_node_view().
 */
function dru_comment_quote_node_view($node, $view_mode) {
  if ($view_mode === 'full' && user_access('post comments') && in_array($node->type, _quote_variable_get('node_types')) && $node->comment == COMMENT_NODE_OPEN && _quote_variable_get('node_link_display')) {
    drupal_add_js(drupal_get_path('module', 'dru_comment_quote') . '/dru-comment-quote.js');
    $node->content['#pre_render'][] = 'dru_comment_quote_link_pre_render';
  }
}

/**
 * Implements hook_preprocess_field().
 */
function dru_comment_quote_preprocess_field(&$variables) {

  if (!in_array($variables['element']['#field_name'], array('body', 'comment_body'))) {
    return;
  }

  $entity = $variables['element']['#object'];
  $user_name = !empty($entity->name) ? $entity->name : variable_get('anonymous', t('Anonymous'));

  if (isset($variables['element']['#source_id'])) {
    $variables['attributes_array']['data-source'][] = $variables['element']['#source_id'];
    $variables['attributes_array']['data-user'][] = $user_name;
  }
}

/**
 * Prepare quote link for node and node comment.
 *
 * @param
 *
 * @return
 */
function dru_comment_quote_link_pre_render($element) {

  if (!isset($element['links']['comment']['#links']['quote'])) {
    return $element;
  }

  // $element['classes_array'][]='comment-quote-source';
  $id = "dru-comment-quote-{$element['#entity_type']}-";

  switch ($element['#entity_type']) {
    case 'node':
      $id .= $element['#node']->nid;
      $element['body']['#source_id'] = $id;
      break;

    case 'comment':
      $id .= $element['#comment']->cid;
      $element['comment_body']['#source_id'] = $id;
      break;
  }

  $element['links']['comment']['#links']['quote']['attributes']['class'][] = 'comment-quote-link';
  $element['links']['comment']['#links']['quote']['attributes']['data-id'] = $id;

  return $element;
}
