deploy:
  master:
    server: 85.143.172.161
    username: drupal
    dir: '{home}/repo'
    env_vars:
      environment: prod
      site: drupal.ru
      store_versions: 3
    scripts:
      after: '{deploy_dir}/profiles/drupalru/scripts/zen.ci/deploy-prod.sh'
  dev:
    server: 89.223.31.105
    username: drupal
    dir: '{home}/repo'
    env_vars:
      environment: dev
      store_versions: 5
    scripts:
      after: '{deploy_dir}/profiles/drupalru/scripts/zen.ci/deploy.sh'
  stage:
    server: 89.223.31.105
    username: drupal
    dir: '{home}/repo'
    env_vars:
      environment: stage
      store_versions: 5
    scripts:
      after: '{deploy_dir}/profiles/drupalru/scripts/zen.ci/deploy.sh'