deploy:
  dev:
    server: drupal.ru
    username: drupal
    dir: '{home}/github/repository'
    env_vars:
      environment: dev
      profile: drupalru
    scripts:
      after: '{deploy_dir}/scripts/deploy.sh'
  stage:
    server: drupal.ru
    username: drupal
    dir: '{home}/github/repository'
    env_vars:
      environment: stage
      profile: drupalru
    scripts:
      after: '{deploy_dir}/scripts/deploy.sh'