<?php
// Font definition based on figlet font "straight" (http://www.figlet.org/)
// as distributed by pyfiglet (http://sourceforge.net/projects/pyfiglet/)

function ASCII_art_captcha_font_straight() {
  $font = array();
  $font['height'] = 4;
  $font['name'] = 'straight';
  $font['comment'] = 'straight.flf\t\tVersion 2by:  Bas Meijer   meijer@info.win.tue.nl   bas@damek.kth.sefixed by: Ryan Youck  youck@cs.uregina.caDisclaimer: most capitals have been designed by someone else';
  $font['a'] = array(
    '    ',
    ' _  ',
    '(_| ',
    '    ',
  );
  $font['b'] = array(
    '    ',
    '|_  ',
    '|_) ',
    '    ',
  );
  $font['c'] = array(
    '   ',
    ' _ ',
    '(_ ',
    '   ',
  );
  $font['d'] = array(
    '    ',
    ' _| ',
    '(_| ',
    '    ',
  );
  $font['e'] = array(
    '   ',
    ' _ ',
    '(- ',
    '   ',
  );
  $font['f'] = array(
    ' _ ',
    '(_ ',
    '|  ',
    '   ',
  );
  $font['g'] = array(
    '    ',
    ' _  ',
    '(_) ',
    '_/  ',
  );
  $font['h'] = array(
    '    ',
    '|_  ',
    '| ) ',
    '    ',
  );
  $font['i'] = array(
    '  ',
    '. ',
    '| ',
    '  ',
  );
  $font['j'] = array(
    '  ',
    '. ',
    '| ',
    '/ ',
  );
  $font['k'] = array(
    '   ',
    '|  ',
    '|( ',
    '   ',
  );
  $font['l'] = array(
    '  ',
    '| ',
    '| ',
    '  ',
  );
  $font['m'] = array(
    '    ',
    ' _  ',
    '||| ',
    '    ',
  );
  $font['n'] = array(
    '    ',
    ' _  ',
    '| ) ',
    '    ',
  );
  $font['o'] = array(
    '    ',
    ' _  ',
    '(_) ',
    '    ',
  );
  $font['p'] = array(
    '    ',
    ' _  ',
    '|_) ',
    '|   ',
  );
  $font['q'] = array(
    '    ',
    ' _  ',
    '(_| ',
    '  | ',
  );
  $font['r'] = array(
    '   ',
    ' _ ',
    '|  ',
    '   ',
  );
  $font['s'] = array(
    '   ',
    ' _ ',
    '_) ',
    '   ',
  );
  $font['t'] = array(
    '   ',
    '|_ ',
    '|_ ',
    '   ',
  );
  $font['u'] = array(
    '    ',
    '    ',
    '|_| ',
    '    ',
  );
  $font['v'] = array(
    '   ',
    '   ',
    '\\/ ',
    '   ',
  );
  $font['w'] = array(
    '    ',
    '    ',
    '\\)/ ',
    '    ',
  );
  $font['x'] = array(
    '   ',
    '   ',
    ')( ',
    '   ',
  );
  $font['y'] = array(
    '   ',
    '   ',
    '\\/ ',
    '/  ',
  );
  $font['z'] = array(
    '   ',
    '_  ',
    '/_ ',
    '   ',
  );
  $font['A'] = array(
    '     ',
    ' /\\  ',
    '/--\\ ',
    '     ',
  );
  $font['B'] = array(
    ' __  ',
    '|__) ',
    '|__) ',
    '     ',
  );
  $font['C'] = array(
    ' __ ',
    '/   ',
    '\\__ ',
    '    ',
  );
  $font['D'] = array(
    ' __  ',
    '|  \\ ',
    '|__/ ',
    '     ',
  );
  $font['E'] = array(
    ' __ ',
    '|_  ',
    '|__ ',
    '    ',
  );
  $font['F'] = array(
    ' __ ',
    '|_  ',
    '|   ',
    '    ',
  );
  $font['G'] = array(
    ' __  ',
    '/ _  ',
    '\\__) ',
    '     ',
  );
  $font['H'] = array(
    '     ',
    '|__| ',
    '|  | ',
    '     ',
  );
  $font['I'] = array(
    '  ',
    '| ',
    '| ',
    '  ',
  );
  $font['J'] = array(
    '    ',
    '  | ',
    '__) ',
    '    ',
  );
  $font['K'] = array(
    '    ',
    '|_/ ',
    '| \\ ',
    '    ',
  );
  $font['L'] = array(
    '    ',
    '|   ',
    '|__ ',
    '    ',
  );
  $font['M'] = array(
    '     ',
    '|\\/| ',
    '|  | ',
    '     ',
  );
  $font['N'] = array(
    '     ',
    '|\\ | ',
    '| \\| ',
    '     ',
  );
  $font['O'] = array(
    ' __  ',
    '/  \\ ',
    '\\__/ ',
    '     ',
  );
  $font['P'] = array(
    ' __  ',
    '|__) ',
    '|    ',
    '     ',
  );
  $font['Q'] = array(
    ' __  ',
    '/  \\ ',
    '\\_\\/ ',
    '     ',
  );
  $font['R'] = array(
    ' __  ',
    '|__) ',
    '| \\  ',
    '     ',
  );
  $font['S'] = array(
    ' __ ',
    '(_  ',
    '__) ',
    '    ',
  );
  $font['T'] = array(
    '___ ',
    ' |  ',
    ' |  ',
    '    ',
  );
  $font['U'] = array(
    '     ',
    '/  \\ ',
    '\\__/ ',
    '     ',
  );
  $font['V'] = array(
    '     ',
    '\\  / ',
    ' \\/  ',
    '     ',
  );
  $font['W'] = array(
    '     ',
    '|  | ',
    '|/\\| ',
    '     ',
  );
  $font['X'] = array(
    '    ',
    '\\_/ ',
    '/ \\ ',
    '    ',
  );
  $font['Y'] = array(
    '    ',
    '\\_/ ',
    ' |  ',
    '    ',
  );
  $font['Z'] = array(
    '___ ',
    ' _/ ',
    '/__ ',
    '    ',
  );
  $font['0'] = array(
    '  __  ',
    ' /  \\ ',
    ' \\__/ ',
    '      ',
  );
  $font['1'] = array(
    '    ',
    ' /| ',
    '  | ',
    '    ',
  );
  $font['2'] = array(
    ' __  ',
    '  _) ',
    ' /__ ',
    '     ',
  );
  $font['3'] = array(
    ' __  ',
    '  _) ',
    ' __) ',
    '     ',
  );
  $font['4'] = array(
    '      ',
    ' |__| ',
    '    | ',
    '      ',
  );
  $font['5'] = array(
    '  __ ',
    ' |_  ',
    ' __) ',
    '     ',
  );
  $font['6'] = array(
    '  __  ',
    ' /__  ',
    ' \\__) ',
    '      ',
  );
  $font['7'] = array(
    ' ___ ',
    '   / ',
    '  /  ',
    '     ',
  );
  $font['8'] = array(
    '  __  ',
    ' (__) ',
    ' (__) ',
    '      ',
  );
  $font['9'] = array(
    '  __  ',
    ' (__\\ ',
    '  __/ ',
    '      ',
  );

  return $font;
}
