<?php
// Font definition based on figlet font "o8" (http://www.figlet.org/)
// as distributed by pyfiglet (http://sourceforge.net/projects/pyfiglet/)

function ASCII_art_captcha_font_o8() {
  $font = array();
  $font['height'] = 6;
  $font['name'] = 'o8';
  $font['comment'] = 'Original font by Gordon Lee <93cmgl@eng.cam.ac.uk>==================================================Original figletization by Tony Nugent (T.Nugent@sct.gu.edu.au)Version 1  - Needs refining with hardblanks and cleaning up of some ofthe characters.  The last 6 chars need to be done properly.==================================================Version 2 by Ian Chai <spectre@uiuc.edu> Added the hardblank fix andthe German characters.==================================================';
  $font['a'] = array(
    '            ',
    '  ooooooo   ',
    '  ooooo888  ',
    '888    888  ',
    ' 88ooo88 8o ',
    '            ',
  );
  $font['b'] = array(
    'oooo        ',
    ' 888ooooo   ',
    ' 888    888 ',
    ' 888    888 ',
    'o888ooo88   ',
    '            ',
  );
  $font['c'] = array(
    '            ',
    '  ooooooo   ',
    '888     888 ',
    '888         ',
    '  88ooo888  ',
    '            ',
  );
  $font['d'] = array(
    '       oooo ',
    '  ooooo888  ',
    '888    888  ',
    '888    888  ',
    '  88ooo888o ',
    '            ',
  );
  $font['e'] = array(
    '            ',
    ' ooooooooo8 ',
    '888oooooo8  ',
    '888         ',
    '  88oooo888 ',
    '            ',
  );
  $font['f'] = array(
    '  o888o ',
    'o888oo  ',
    ' 888    ',
    ' 888    ',
    'o888o   ',
    '        ',
  );
  $font['g'] = array(
    '            ',
    '  oooooooo8 ',
    '888    88o  ',
    ' 888oo888o  ',
    '888     888 ',
    ' 888ooo888  ',
  );
  $font['h'] = array(
    'oooo        ',
    ' 888ooooo   ',
    ' 888   888  ',
    ' 888   888  ',
    'o888o o888o ',
    '            ',
  );
  $font['i'] = array(
    'o88   ',
    'oooo  ',
    ' 888  ',
    ' 888  ',
    'o888o ',
    '      ',
  );
  $font['j'] = array(
    ' o88 ',
    'oooo ',
    ' 888 ',
    ' 888 ',
    ' 888 ',
    'o88  ',
  );
  $font['k'] = array(
    'oooo        ',
    ' 888  ooooo ',
    ' 888o888    ',
    ' 8888 88o   ',
    'o888o o888o ',
    '            ',
  );
  $font['l'] = array(
    'o888  ',
    ' 888  ',
    ' 888  ',
    ' 888  ',
    'o888o ',
    '      ',
  );
  $font['m'] = array(
    '              ',
    'oo ooo oooo   ',
    ' 888 888 888  ',
    ' 888 888 888  ',
    'o888o888o888o ',
    '              ',
  );
  $font['n'] = array(
    '            ',
    'oo oooooo   ',
    ' 888   888  ',
    ' 888   888  ',
    'o888o o888o ',
    '            ',
  );
  $font['o'] = array(
    '            ',
    '  ooooooo   ',
    '888     888 ',
    '888     888 ',
    '  88ooo88   ',
    '            ',
  );
  $font['p'] = array(
    '            ',
    'ooooooooo   ',
    ' 888    888 ',
    ' 888    888 ',
    ' 888ooo88   ',
    'o888        ',
  );
  $font['q'] = array(
    '            ',
    '  ooooooooo ',
    '888    888  ',
    '888    888  ',
    '  88ooo888  ',
    '       888o ',
  );
  $font['r'] = array(
    '            ',
    'oo oooooo   ',
    ' 888    888 ',
    ' 888        ',
    'o888o       ',
    '            ',
  );
  $font['s'] = array(
    '            ',
    ' oooooooo8  ',
    '888ooooooo  ',
    '        888 ',
    '88oooooo88  ',
    '            ',
  );
  $font['t'] = array(
    '  o8   ',
    'o888oo ',
    ' 888   ',
    ' 888   ',
    '  888o ',
    '       ',
  );
  $font['u'] = array(
    '            ',
    'oooo  oooo  ',
    ' 888   888  ',
    ' 888   888  ',
    '  888o88 8o ',
    '            ',
  );
  $font['v'] = array(
    '            ',
    'oooo   oooo ',
    ' 888   888  ',
    '  888 888   ',
    '    888     ',
    '            ',
  );
  $font['w'] = array(
    '              ',
    'oooo  o  oooo ',
    ' 888 888 888  ',
    '  888888888   ',
    '   88   88    ',
    '              ',
  );
  $font['x'] = array(
    '            ',
    'oooo   oooo ',
    '  888o888   ',
    '  o88 88o   ',
    'o88o   o88o ',
    '            ',
  );
  $font['y'] = array(
    '            ',
    'oooo   oooo ',
    ' 888   888  ',
    '  888 888   ',
    '    8888    ',
    ' o8o888     ',
  );
  $font['z'] = array(
    '            ',
    'ooooooooooo ',
    '     8888   ',
    '  8888      ',
    'o888ooooooo ',
    '            ',
  );
  $font['A'] = array(
    '     o      ',
    '    888     ',
    '   8  88    ',
    '  8oooo88   ',
    'o88o  o888o ',
    '            ',
  );
  $font['B'] = array(
    'oooooooooo  ',
    ' 888    888 ',
    ' 888oooo88  ',
    ' 888    888 ',
    'o888ooo888  ',
    '            ',
  );
  $font['C'] = array(
    '  oooooooo8 ',
    'o888     88 ',
    '888         ',
    '888o     oo ',
    ' 888oooo88  ',
    '            ',
  );
  $font['D'] = array(
    'ooooooooo   ',
    ' 888    88o ',
    ' 888    888 ',
    ' 888    888 ',
    'o888ooo88   ',
    '            ',
  );
  $font['E'] = array(
    'ooooooooooo ',
    ' 888    88  ',
    ' 888ooo8    ',
    ' 888    oo  ',
    'o888ooo8888 ',
    '            ',
  );
  $font['F'] = array(
    'ooooooooooo ',
    ' 888    88  ',
    ' 888ooo8    ',
    ' 888        ',
    'o888o       ',
    '            ',
  );
  $font['G'] = array(
    '  ooooooo8  ',
    'o888    88  ',
    '888    oooo ',
    '888o    88  ',
    ' 888ooo888  ',
    '            ',
  );
  $font['H'] = array(
    'ooooo ooooo ',
    ' 888   888  ',
    ' 888ooo888  ',
    ' 888   888  ',
    'o888o o888o ',
    '            ',
  );
  $font['I'] = array(
    'ooooo ',
    ' 888  ',
    ' 888  ',
    ' 888  ',
    'o888o ',
    '      ',
  );
  $font['J'] = array(
    '  ooooo ',
    '   888  ',
    '   888  ',
    '   888  ',
    '   888  ',
    '8o888   ',
  );
  $font['K'] = array(
    'oooo   oooo ',
    ' 888  o88   ',
    ' 888888     ',
    ' 888  88o   ',
    'o888o o888o ',
    '            ',
  );
  $font['L'] = array(
    'ooooo       ',
    ' 888        ',
    ' 888        ',
    ' 888      o ',
    'o888ooooo88 ',
    '            ',
  );
  $font['M'] = array(
    'oooo     oooo ',
    ' 8888o   888  ',
    ' 88 888o8 88  ',
    ' 88  888  88  ',
    'o88o  8  o88o ',
    '              ',
  );
  $font['N'] = array(
    'oooo   oooo ',
    ' 8888o  88  ',
    ' 88 888o88  ',
    ' 88   8888  ',
    'o88o    88  ',
    '            ',
  );
  $font['O'] = array(
    '  ooooooo   ',
    'o888   888o ',
    '888     888 ',
    '888o   o888 ',
    '  88ooo88   ',
    '            ',
  );
  $font['P'] = array(
    'oooooooooo  ',
    ' 888    888 ',
    ' 888oooo88  ',
    ' 888        ',
    'o888o       ',
    '            ',
  );
  $font['Q'] = array(
    '  ooooooo   ',
    'o888   888o ',
    '888     888 ',
    '888o  8o888 ',
    '  88ooo88   ',
    '       88o8 ',
  );
  $font['R'] = array(
    'oooooooooo  ',
    ' 888    888 ',
    ' 888oooo88  ',
    ' 888  88o   ',
    'o888o  88o8 ',
    '            ',
  );
  $font['S'] = array(
    ' oooooooo8  ',
    '888         ',
    ' 888oooooo  ',
    '        888 ',
    'o88oooo888  ',
    '            ',
  );
  $font['T'] = array(
    'ooooooooooo ',
    '88  888  88 ',
    '    888     ',
    '    888     ',
    '   o888o    ',
    '            ',
  );
  $font['U'] = array(
    'ooooo  oooo ',
    ' 888    88  ',
    ' 888    88  ',
    ' 888    88  ',
    '  888oo88   ',
    '            ',
  );
  $font['V'] = array(
    'ooooo  oooo ',
    ' 888    88  ',
    '  888  88   ',
    '   88888    ',
    '    888     ',
    '            ',
  );
  $font['W'] = array(
    'oooo     oooo ',
    ' 88   88  88  ',
    '  88 888 88   ',
    '   888 888    ',
    '    8   8     ',
    '              ',
  );
  $font['X'] = array(
    'ooooo  oooo ',
    '  888  88   ',
    '    888     ',
    '   88 888   ',
    'o88o  o888o ',
    '            ',
  );
  $font['Y'] = array(
    'ooooo  oooo ',
    '  888  88   ',
    '    888     ',
    '    888     ',
    '   o888o    ',
    '            ',
  );
  $font['Z'] = array(
    'ooooooooooo ',
    '88    888   ',
    '    888     ',
    '  888    oo ',
    'o888oooo888 ',
    '            ',
  );
  $font['0'] = array(
    '  ooooooo   ',
    'o888  o888o ',
    '888  8  888 ',
    '888o8  o888 ',
    '  88ooo88   ',
    '            ',
  );
  $font['1'] = array(
    '  oo  ',
    'o888  ',
    ' 888  ',
    ' 888  ',
    'o888o ',
    '      ',
  );
  $font['2'] = array(
    '  ooooooo   ',
    'o88     888 ',
    '      o888  ',
    '   o888   o ',
    'o8888oooo88 ',
    '            ',
  );
  $font['3'] = array(
    '  ooooooo   ',
    'o88    888o ',
    '    88888o  ',
    '88o    o888 ',
    '  88ooo88   ',
    '            ',
  );
  $font['4'] = array(
    '      o88   ',
    '    o8888   ',
    '  o88 888   ',
    'o888oo888oo ',
    '     o888o  ',
    '            ',
  );
  $font['5'] = array(
    'oooooooooo  ',
    '888         ',
    '888888888o  ',
    'ooo    o888 ',
    '  88ooo88   ',
    '            ',
  );
  $font['6'] = array(
    '  ooooooo   ',
    'o88         ',
    '888888888o  ',
    '88o    o888 ',
    '  88ooo88   ',
    '            ',
  );
  $font['7'] = array(
    'ooooooooooo ',
    '888    888  ',
    '      888   ',
    '     888    ',
    '    888     ',
    '            ',
  );
  $font['8'] = array(
    '  ooooooo   ',
    'o888   888o ',
    ' 888888888  ',
    '888o   o888 ',
    '  88ooo88   ',
    '            ',
  );
  $font['9'] = array(
    ' ooooooo   ',
    '888    88o ',
    ' 888oo8888 ',
    '      888  ',
    '   o888    ',
    '           ',
  );

  return $font;
}
