<?php
// Font definition based on figlet font "smslant" (http://www.figlet.org/)
// as distributed by pyfiglet (http://sourceforge.net/projects/pyfiglet/)

function ASCII_art_captcha_font_smslant() {
  $font = array();
  $font['height'] = 5;
  $font['name'] = 'smslant';
  $font['comment'] = 'SmSlant by Glenn Chappell 6/93 - based on Small & SlantIncludes ISO Latin-1figlet release 2.1 -- 12 Aug 1994Permission is hereby given to modify this font, as long as themodifier\'s name is placed on a comment line.Modified by Paul Burton <solution@earthlink.net> 12/96 to include new parametersupported by FIGlet and FIGWin.  May also be slightly modified for better useof new full-width/kern/smush alternatives, but default output is NOT changed.';
  $font['a'] = array(
    '      ',
    ' ___ _',
    '/ _ `/',
    '\\_,_/ ',
    '      ',
  );
  $font['b'] = array(
    '   __ ',
    '  / / ',
    ' / _ \\',
    '/_.__/',
    '      ',
  );
  $font['c'] = array(
    '     ',
    ' ____',
    '/ __/',
    '\\__/ ',
    '     ',
  );
  $font['d'] = array(
    '     __',
    ' ___/ /',
    '/ _  / ',
    '\\_,_/  ',
    '       ',
  );
  $font['e'] = array(
    '     ',
    ' ___ ',
    '/ -_)',
    '\\__/ ',
    '     ',
  );
  $font['f'] = array(
    '   ___',
    '  / _/',
    ' / _/ ',
    '/_/   ',
    '      ',
  );
  $font['g'] = array(
    '       ',
    '  ___ _',
    ' / _ `/',
    ' \\_, / ',
    '/___/  ',
  );
  $font['h'] = array(
    '   __ ',
    '  / / ',
    ' / _ \\',
    '/_//_/',
    '      ',
  );
  $font['i'] = array(
    '   _ ',
    '  (_)',
    ' / / ',
    '/_/  ',
    '     ',
  );
  $font['j'] = array(
    '      _ ',
    '     (_)',
    '    / / ',
    ' __/ /  ',
    '|___/   ',
  );
  $font['k'] = array(
    '   __  ',
    '  / /__',
    ' /  \'_/',
    '/_/\\_\\ ',
    '       ',
  );
  $font['l'] = array(
    '   __',
    '  / /',
    ' / / ',
    '/_/  ',
    '     ',
  );
  $font['m'] = array(
    '       ',
    '  __ _ ',
    ' /  \' \\',
    '/_/_/_/',
    '       ',
  );
  $font['n'] = array(
    '      ',
    '  ___ ',
    ' / _ \\',
    '/_//_/',
    '      ',
  );
  $font['o'] = array(
    '     ',
    ' ___ ',
    '/ _ \\',
    '\\___/',
    '     ',
  );
  $font['p'] = array(
    '       ',
    '   ___ ',
    '  / _ \\',
    ' / .__/',
    '/_/    ',
  );
  $font['q'] = array(
    '      ',
    ' ___ _',
    '/ _ `/',
    '\\_, / ',
    ' /_/  ',
  );
  $font['r'] = array(
    '      ',
    '  ____',
    ' / __/',
    '/_/   ',
    '      ',
  );
  $font['s'] = array(
    '     ',
    '  ___',
    ' (_-<',
    '/___/',
    '     ',
  );
  $font['t'] = array(
    '  __ ',
    ' / /_',
    '/ __/',
    '\\__/ ',
    '     ',
  );
  $font['u'] = array(
    '      ',
    ' __ __',
    '/ // /',
    '\\_,_/ ',
    '      ',
  );
  $font['v'] = array(
    '      ',
    ' _  __',
    '| |/ /',
    '|___/ ',
    '      ',
  );
  $font['w'] = array(
    '        ',
    ' _    __',
    '| |/|/ /',
    '|__,__/ ',
    '        ',
  );
  $font['x'] = array(
    '      ',
    ' __ __',
    ' \\ \\ /',
    '/_\\_\\ ',
    '      ',
  );
  $font['y'] = array(
    '       ',
    '  __ __',
    ' / // /',
    ' \\_, / ',
    '/___/  ',
  );
  $font['z'] = array(
    '    ',
    ' ___',
    '/_ /',
    '/__/',
    '    ',
  );
  $font['A'] = array(
    '   ___ ',
    '  / _ |',
    ' / __ |',
    '/_/ |_|',
    '       ',
  );
  $font['B'] = array(
    '   ___ ',
    '  / _ )',
    ' / _  |',
    '/____/ ',
    '       ',
  );
  $font['C'] = array(
    '  _____',
    ' / ___/',
    '/ /__  ',
    '\\___/  ',
    '       ',
  );
  $font['D'] = array(
    '   ___ ',
    '  / _ \\',
    ' / // /',
    '/____/ ',
    '       ',
  );
  $font['E'] = array(
    '   ____',
    '  / __/',
    ' / _/  ',
    '/___/  ',
    '       ',
  );
  $font['F'] = array(
    '   ____',
    '  / __/',
    ' / _/  ',
    '/_/    ',
    '       ',
  );
  $font['G'] = array(
    '  _____',
    ' / ___/',
    '/ (_ / ',
    '\\___/  ',
    '       ',
  );
  $font['H'] = array(
    '   __ __',
    '  / // /',
    ' / _  / ',
    '/_//_/  ',
    '        ',
  );
  $font['I'] = array(
    '   ____',
    '  /  _/',
    ' _/ /  ',
    '/___/  ',
    '       ',
  );
  $font['J'] = array(
    '     __',
    ' __ / /',
    '/ // / ',
    '\\___/  ',
    '       ',
  );
  $font['K'] = array(
    '   __ __',
    '  / //_/',
    ' / ,<   ',
    '/_/|_|  ',
    '        ',
  );
  $font['L'] = array(
    '   __ ',
    '  / / ',
    ' / /__',
    '/____/',
    '      ',
  );
  $font['M'] = array(
    '   __  ___',
    '  /  |/  /',
    ' / /|_/ / ',
    '/_/  /_/  ',
    '          ',
  );
  $font['N'] = array(
    '   _  __',
    '  / |/ /',
    ' /    / ',
    '/_/|_/  ',
    '        ',
  );
  $font['O'] = array(
    '  ____ ',
    ' / __ \\',
    '/ /_/ /',
    '\\____/ ',
    '       ',
  );
  $font['P'] = array(
    '   ___ ',
    '  / _ \\',
    ' / ___/',
    '/_/    ',
    '       ',
  );
  $font['Q'] = array(
    '  ____ ',
    ' / __ \\',
    '/ /_/ /',
    '\\___\\_\\',
    '       ',
  );
  $font['R'] = array(
    '   ___ ',
    '  / _ \\',
    ' / , _/',
    '/_/|_| ',
    '       ',
  );
  $font['S'] = array(
    '   ____',
    '  / __/',
    ' _\\ \\  ',
    '/___/  ',
    '       ',
  );
  $font['T'] = array(
    ' ______',
    '/_  __/',
    ' / /   ',
    '/_/    ',
    '       ',
  );
  $font['U'] = array(
    '  __  __',
    ' / / / /',
    '/ /_/ / ',
    '\\____/  ',
    '        ',
  );
  $font['V'] = array(
    ' _   __',
    '| | / /',
    '| |/ / ',
    '|___/  ',
    '       ',
  );
  $font['W'] = array(
    ' _      __',
    '| | /| / /',
    '| |/ |/ / ',
    '|__/|__/  ',
    '          ',
  );
  $font['X'] = array(
    '   _  __',
    '  | |/_/',
    ' _>  <  ',
    '/_/|_|  ',
    '        ',
  );
  $font['Y'] = array(
    '__  __',
    '\\ \\/ /',
    ' \\  / ',
    ' /_/  ',
    '      ',
  );
  $font['Z'] = array(
    ' ____',
    '/_  /',
    ' / /_',
    '/___/',
    '     ',
  );
  $font['0'] = array(
    '  ___ ',
    ' / _ \\',
    '/ // /',
    '\\___/ ',
    '      ',
  );
  $font['1'] = array(
    '  ___',
    ' <  /',
    ' / / ',
    '/_/  ',
    '     ',
  );
  $font['2'] = array(
    '   ___ ',
    '  |_  |',
    ' / __/ ',
    '/____/ ',
    '       ',
  );
  $font['3'] = array(
    '   ____',
    '  |_  /',
    ' _/_ < ',
    '/____/ ',
    '       ',
  );
  $font['4'] = array(
    '  ____',
    ' / / /',
    '/_  _/',
    ' /_/  ',
    '      ',
  );
  $font['5'] = array(
    '   ____',
    '  / __/',
    ' /__ \\ ',
    '/____/ ',
    '       ',
  );
  $font['6'] = array(
    '  ____',
    ' / __/',
    '/ _ \\ ',
    '\\___/ ',
    '      ',
  );
  $font['7'] = array(
    ' ____',
    '/_  /',
    ' / / ',
    '/_/  ',
    '     ',
  );
  $font['8'] = array(
    '  ___ ',
    ' ( _ )',
    '/ _  |',
    '\\___/ ',
    '      ',
  );
  $font['9'] = array(
    '  ___ ',
    ' / _ \\',
    ' \\_, /',
    '/___/ ',
    '      ',
  );

  return $font;
}
