<?php
// Font definition based on figlet font "letters" (http://www.figlet.org/)
// as distributed by pyfiglet (http://sourceforge.net/projects/pyfiglet/)

function ASCII_art_captcha_font_letters() {
  $font = array();
  $font['height'] = 6;
  $font['name'] = 'letters';
  $font['comment'] = 'Letters by Sriram J. Gollapalli,  July 10, 1994  o__         +----------------------+          __o _.>/)_       | Sriram J. Gollapalli |        _(\\<._(_) \\(_)      +----------------------+       (_)/ (_)                 <sriram@capaccess.org>';
  $font['a'] = array(
    '        ',
    '  aa aa ',
    ' aa aaa ',
    'aa  aaa ',
    ' aaa aa ',
    '        ',
  );
  $font['b'] = array(
    'bb      ',
    'bb      ',
    'bbbbbb  ',
    'bb   bb ',
    'bbbbbb  ',
    '        ',
  );
  $font['c'] = array(
    '       ',
    '  cccc ',
    'cc     ',
    'cc     ',
    ' ccccc ',
    '       ',
  );
  $font['d'] = array(
    '     dd ',
    '     dd ',
    ' dddddd ',
    'dd   dd ',
    ' dddddd ',
    '        ',
  );
  $font['e'] = array(
    '       ',
    '  eee  ',
    'ee   e ',
    'eeeee  ',
    ' eeeee ',
    '       ',
  );
  $font['f'] = array(
    ' fff ',
    'ff   ',
    'ffff ',
    'ff   ',
    'ff   ',
    '     ',
  );
  $font['g'] = array(
    '        ',
    ' gggggg ',
    'gg   gg ',
    'ggggggg ',
    '     gg ',
    ' ggggg  ',
  );
  $font['h'] = array(
    'hh      ',
    'hh      ',
    'hhhhhh  ',
    'hh   hh ',
    'hh   hh ',
    '        ',
  );
  $font['i'] = array(
    'iii ',
    '    ',
    'iii ',
    'iii ',
    'iii ',
    '    ',
  );
  $font['j'] = array(
    '  jjj ',
    '      ',
    '  jjj ',
    '  jjj ',
    '  jjj ',
    'jjjj  ',
  );
  $font['k'] = array(
    'kk     ',
    'kk  kk ',
    'kkkkk  ',
    'kk kk  ',
    'kk  kk ',
    '       ',
  );
  $font['l'] = array(
    'lll ',
    'lll ',
    'lll ',
    'lll ',
    'lll ',
    '    ',
  );
  $font['m'] = array(
    '            ',
    'mm mm mmmm  ',
    'mmm  mm  mm ',
    'mmm  mm  mm ',
    'mmm  mm  mm ',
    '            ',
  );
  $font['n'] = array(
    '        ',
    'nn nnn  ',
    'nnn  nn ',
    'nn   nn ',
    'nn   nn ',
    '        ',
  );
  $font['o'] = array(
    '       ',
    ' oooo  ',
    'oo  oo ',
    'oo  oo ',
    ' oooo  ',
    '       ',
  );
  $font['p'] = array(
    '        ',
    'pp pp   ',
    'ppp  pp ',
    'pppppp  ',
    'pp      ',
    'pp      ',
  );
  $font['q'] = array(
    '        ',
    '  qqqqq ',
    'qq   qq ',
    ' qqqqqq ',
    '     qq ',
    '     qq ',
  );
  $font['r'] = array(
    '       ',
    'rr rr  ',
    'rrr  r ',
    'rr     ',
    'rr     ',
    '       ',
  );
  $font['s'] = array(
    '      ',
    ' sss  ',
    's     ',
    ' sss  ',
    '    s ',
    ' sss  ',
  );
  $font['t'] = array(
    'tt    ',
    'tt    ',
    'tttt  ',
    'tt    ',
    ' tttt ',
    '      ',
  );
  $font['u'] = array(
    '        ',
    'uu   uu ',
    'uu   uu ',
    'uu   uu ',
    ' uuuu u ',
    '        ',
  );
  $font['v'] = array(
    '        ',
    'vv   vv ',
    ' vv vv  ',
    '  vvv   ',
    '   v    ',
    '        ',
  );
  $font['w'] = array(
    '           ',
    'ww      ww ',
    'ww      ww ',
    ' ww ww ww  ',
    '  ww  ww   ',
    '           ',
  );
  $font['x'] = array(
    '       ',
    'xx  xx ',
    '  xx   ',
    '  xx   ',
    'xx  xx ',
    '       ',
  );
  $font['y'] = array(
    '        ',
    'yy   yy ',
    'yy   yy ',
    ' yyyyyy ',
    '     yy ',
    ' yyyyy  ',
  );
  $font['z'] = array(
    '      ',
    'zzzzz ',
    '  zz  ',
    ' zz   ',
    'zzzzz ',
    '      ',
  );
  $font['A'] = array(
    '  AAA   ',
    ' AAAAA  ',
    'AA   AA ',
    'AAAAAAA ',
    'AA   AA ',
    '        ',
  );
  $font['B'] = array(
    'BBBBB   ',
    'BB   B  ',
    'BBBBBB  ',
    'BB   BB ',
    'BBBBBB  ',
    '        ',
  );
  $font['C'] = array(
    ' CCCCC  ',
    'CC    C ',
    'CC      ',
    'CC    C ',
    ' CCCCC  ',
    '        ',
  );
  $font['D'] = array(
    'DDDDD   ',
    'DD  DD  ',
    'DD   DD ',
    'DD   DD ',
    'DDDDDD  ',
    '        ',
  );
  $font['E'] = array(
    'EEEEEEE ',
    'EE      ',
    'EEEEE   ',
    'EE      ',
    'EEEEEEE ',
    '        ',
  );
  $font['F'] = array(
    'FFFFFFF ',
    'FF      ',
    'FFFF    ',
    'FF      ',
    'FF      ',
    '        ',
  );
  $font['G'] = array(
    '  GGGG  ',
    ' GG  GG ',
    'GG      ',
    'GG   GG ',
    ' GGGGGG ',
    '        ',
  );
  $font['H'] = array(
    'HH   HH ',
    'HH   HH ',
    'HHHHHHH ',
    'HH   HH ',
    'HH   HH ',
    '        ',
  );
  $font['I'] = array(
    'IIIII ',
    ' III  ',
    ' III  ',
    ' III  ',
    'IIIII ',
    '      ',
  );
  $font['J'] = array(
    '    JJJ ',
    '    JJJ ',
    '    JJJ ',
    'JJ  JJJ ',
    ' JJJJJ  ',
    '        ',
  );
  $font['K'] = array(
    'KK  KK ',
    'KK KK  ',
    'KKKK   ',
    'KK KK  ',
    'KK  KK ',
    '       ',
  );
  $font['L'] = array(
    'LL      ',
    'LL      ',
    'LL      ',
    'LL      ',
    'LLLLLLL ',
    '        ',
  );
  $font['M'] = array(
    'MM    MM ',
    'MMM  MMM ',
    'MM MM MM ',
    'MM    MM ',
    'MM    MM ',
    '         ',
  );
  $font['N'] = array(
    'NN   NN ',
    'NNN  NN ',
    'NN N NN ',
    'NN  NNN ',
    'NN   NN ',
    '        ',
  );
  $font['O'] = array(
    ' OOOOO  ',
    'OO   OO ',
    'OO   OO ',
    'OO   OO ',
    ' OOOO0  ',
    '        ',
  );
  $font['P'] = array(
    'PPPPPP  ',
    'PP   PP ',
    'PPPPPP  ',
    'PP      ',
    'PP      ',
    '        ',
  );
  $font['Q'] = array(
    ' QQQQQ  ',
    'QQ   QQ ',
    'QQ   QQ ',
    'QQ  QQ  ',
    ' QQQQ Q ',
    '        ',
  );
  $font['R'] = array(
    'RRRRRR  ',
    'RR   RR ',
    'RRRRRR  ',
    'RR  RR  ',
    'RR   RR ',
    '        ',
  );
  $font['S'] = array(
    ' SSSSS  ',
    'SS      ',
    ' SSSSS  ',
    '     SS ',
    ' SSSSS  ',
    '        ',
  );
  $font['T'] = array(
    'TTTTTTT ',
    '  TTT   ',
    '  TTT   ',
    '  TTT   ',
    '  TTT   ',
    '        ',
  );
  $font['U'] = array(
    'UU   UU ',
    'UU   UU ',
    'UU   UU ',
    'UU   UU ',
    ' UUUUU  ',
    '        ',
  );
  $font['V'] = array(
    'VV     VV ',
    'VV     VV ',
    ' VV   VV  ',
    '  VV VV   ',
    '   VVV    ',
    '          ',
  );
  $font['W'] = array(
    'WW      WW ',
    'WW      WW ',
    'WW   W  WW ',
    ' WW WWW WW ',
    '  WW   WW  ',
    '           ',
  );
  $font['X'] = array(
    'XX    XX ',
    ' XX  XX  ',
    '  XXXX   ',
    ' XX  XX  ',
    'XX    XX ',
    '         ',
  );
  $font['Y'] = array(
    'YY   YY ',
    'YY   YY ',
    ' YYYYY  ',
    '  YYY   ',
    '  YYY   ',
    '        ',
  );
  $font['Z'] = array(
    'ZZZZZ ',
    '   ZZ ',
    '  ZZ  ',
    ' ZZ   ',
    'ZZZZZ ',
    '      ',
  );
  $font['0'] = array(
    ' 00000  ',
    '00   00 ',
    '00   00 ',
    '00   00 ',
    ' 00000  ',
    '        ',
  );
  $font['1'] = array(
    ' 1  ',
    '111 ',
    ' 11 ',
    ' 11 ',
    '111 ',
    '    ',
  );
  $font['2'] = array(
    ' 2222   ',
    '222222  ',
    '    222 ',
    ' 2222   ',
    '2222222 ',
    '        ',
  );
  $font['3'] = array(
    '333333  ',
    '   3333 ',
    '  3333  ',
    '    333 ',
    '333333  ',
    '        ',
  );
  $font['4'] = array(
    '    44   ',
    '   444   ',
    ' 44  4   ',
    '44444444 ',
    '   444   ',
    '         ',
  );
  $font['5'] = array(
    '555555  ',
    '55      ',
    '555555  ',
    '   5555 ',
    '555555  ',
    '        ',
  );
  $font['6'] = array(
    '  666   ',
    ' 66     ',
    '666666  ',
    '66   66 ',
    ' 66666  ',
    '        ',
  );
  $font['7'] = array(
    '7777777 ',
    '    777 ',
    '   777  ',
    '  777   ',
    ' 777    ',
    '        ',
  );
  $font['8'] = array(
    ' 88888  ',
    '88   88 ',
    ' 88888  ',
    '88   88 ',
    ' 88888  ',
    '        ',
  );
  $font['9'] = array(
    '        ',
    ' 99999  ',
    '99   99 ',
    ' 999999 ',
    '    99  ',
    '  999   ',
  );

  return $font;
}
