<?php
// Font definition based on figlet font "mini" (http://www.figlet.org/)
// as distributed by pyfiglet (http://sourceforge.net/projects/pyfiglet/)

function ASCII_art_captcha_font_mini() {
  $font = array();
  $font['height'] = 4;
  $font['name'] = 'mini';
  $font['comment'] = 'Mini by Glenn Chappell 4/93Includes ISO Latin-1figlet release 2.1 -- 12 Aug 1994Permission is hereby given to modify this font, as long as themodifier\'s name is placed on a comment line.Modified by Paul Burton <solution@earthlink.net> 12/96 to include new parametersupported by FIGlet and FIGWin.  May also be slightly modified for better useof new full-width/kern/smush alternatives, but default output is NOT changed.';
  $font['a'] = array(
    '    ',
    ' _. ',
    '(_| ',
    '    ',
  );
  $font['b'] = array(
    '    ',
    '|_  ',
    '|_) ',
    '    ',
  );
  $font['c'] = array(
    '   ',
    ' _ ',
    '(_ ',
    '   ',
  );
  $font['d'] = array(
    '    ',
    ' _| ',
    '(_| ',
    '    ',
  );
  $font['e'] = array(
    '    ',
    ' _  ',
    '(/_ ',
    '    ',
  );
  $font['f'] = array(
    '  _ ',
    '_|_ ',
    ' |  ',
    '    ',
  );
  $font['g'] = array(
    '    ',
    ' _  ',
    '(_| ',
    ' _| ',
  );
  $font['h'] = array(
    '    ',
    '|_  ',
    '| | ',
    '    ',
  );
  $font['i'] = array(
    '  ',
    'o ',
    '| ',
    '  ',
  );
  $font['j'] = array(
    '   ',
    ' o ',
    ' | ',
    '_| ',
  );
  $font['k'] = array(
    '   ',
    '|  ',
    '|< ',
    '   ',
  );
  $font['l'] = array(
    '  ',
    '| ',
    '| ',
    '  ',
  );
  $font['m'] = array(
    '      ',
    '._ _  ',
    '| | | ',
    '      ',
  );
  $font['n'] = array(
    '    ',
    '._  ',
    '| | ',
    '    ',
  );
  $font['o'] = array(
    '    ',
    ' _  ',
    '(_) ',
    '    ',
  );
  $font['p'] = array(
    '    ',
    '._  ',
    '|_) ',
    '|   ',
  );
  $font['q'] = array(
    '    ',
    ' _. ',
    '(_| ',
    '  | ',
  );
  $font['r'] = array(
    '   ',
    '._ ',
    '|  ',
    '   ',
  );
  $font['s'] = array(
    '   ',
    ' _ ',
    '_> ',
    '   ',
  );
  $font['t'] = array(
    '    ',
    '_|_ ',
    ' |_ ',
    '    ',
  );
  $font['u'] = array(
    '    ',
    '    ',
    '|_| ',
    '    ',
  );
  $font['v'] = array(
    '   ',
    '   ',
    '\\/ ',
    '   ',
  );
  $font['w'] = array(
    '     ',
    '     ',
    '\\/\\/ ',
    '     ',
  );
  $font['x'] = array(
    '   ',
    '   ',
    '>< ',
    '   ',
  );
  $font['y'] = array(
    '   ',
    '   ',
    '\\/ ',
    '/  ',
  );
  $font['z'] = array(
    '   ',
    '_  ',
    '/_ ',
    '   ',
  );
  $font['A'] = array(
    '     ',
    ' /\\  ',
    '/--\\ ',
    '     ',
  );
  $font['B'] = array(
    ' _  ',
    '|_) ',
    '|_) ',
    '    ',
  );
  $font['C'] = array(
    ' _ ',
    '/  ',
    '\\_ ',
    '   ',
  );
  $font['D'] = array(
    ' _  ',
    '| \\ ',
    '|_/ ',
    '    ',
  );
  $font['E'] = array(
    ' _ ',
    '|_ ',
    '|_ ',
    '   ',
  );
  $font['F'] = array(
    ' _ ',
    '|_ ',
    '|  ',
    '   ',
  );
  $font['G'] = array(
    ' __ ',
    '/__ ',
    '\\_| ',
    '    ',
  );
  $font['H'] = array(
    '    ',
    '|_| ',
    '| | ',
    '    ',
  );
  $font['I'] = array(
    '___ ',
    ' |  ',
    '_|_ ',
    '    ',
  );
  $font['J'] = array(
    '    ',
    '  | ',
    '\\_| ',
    '    ',
  );
  $font['K'] = array(
    '   ',
    '|/ ',
    '|\\ ',
    '   ',
  );
  $font['L'] = array(
    '   ',
    '|  ',
    '|_ ',
    '   ',
  );
  $font['M'] = array(
    '     ',
    '|\\/| ',
    '|  | ',
    '     ',
  );
  $font['N'] = array(
    '     ',
    '|\\ | ',
    '| \\| ',
    '     ',
  );
  $font['O'] = array(
    ' _  ',
    '/ \\ ',
    '\\_/ ',
    '    ',
  );
  $font['P'] = array(
    ' _  ',
    '|_) ',
    '|   ',
    '    ',
  );
  $font['Q'] = array(
    ' _  ',
    '/ \\ ',
    '\\_X ',
    '    ',
  );
  $font['R'] = array(
    ' _  ',
    '|_) ',
    '| \\ ',
    '    ',
  );
  $font['S'] = array(
    ' __ ',
    '(_  ',
    '__) ',
    '    ',
  );
  $font['T'] = array(
    '___ ',
    ' |  ',
    ' |  ',
    '    ',
  );
  $font['U'] = array(
    '    ',
    '| | ',
    '|_| ',
    '    ',
  );
  $font['V'] = array(
    '     ',
    '\\  / ',
    ' \\/  ',
    '     ',
  );
  $font['W'] = array(
    '       ',
    '\\    / ',
    ' \\/\\/  ',
    '       ',
  );
  $font['X'] = array(
    '   ',
    '\\/ ',
    '/\\ ',
    '   ',
  );
  $font['Y'] = array(
    '    ',
    '\\_/ ',
    ' |  ',
    '    ',
  );
  $font['Z'] = array(
    '__ ',
    ' / ',
    '/_ ',
    '   ',
  );
  $font['0'] = array(
    ' _  ',
    '/ \\ ',
    '\\_/ ',
    '    ',
  );
  $font['1'] = array(
    '   ',
    '/| ',
    ' | ',
    '   ',
  );
  $font['2'] = array(
    '_  ',
    ' ) ',
    '/_ ',
    '   ',
  );
  $font['3'] = array(
    '_  ',
    '_) ',
    '_) ',
    '   ',
  );
  $font['4'] = array(
    '     ',
    '|_|_ ',
    '  |  ',
    '     ',
  );
  $font['5'] = array(
    ' _  ',
    '|_  ',
    ' _) ',
    '    ',
  );
  $font['6'] = array(
    ' _  ',
    '|_  ',
    '|_) ',
    '    ',
  );
  $font['7'] = array(
    '__ ',
    ' / ',
    '/  ',
    '   ',
  );
  $font['8'] = array(
    ' _  ',
    '(_) ',
    '(_) ',
    '    ',
  );
  $font['9'] = array(
    ' _  ',
    '(_| ',
    '  | ',
    '    ',
  );

  return $font;
}
