<?php
// Font definition based on figlet font "small" (http://www.figlet.org/)
// as distributed by pyfiglet (http://sourceforge.net/projects/pyfiglet/)

function ASCII_art_captcha_font_small() {
  $font = array();
  $font['height'] = 5;
  $font['name'] = 'small';
  $font['comment'] = 'Small by Glenn Chappell 4/93 -- based on StandardIncludes ISO Latin-1figlet release 2.1 -- 12 Aug 1994Permission is hereby given to modify this font, as long as themodifier\'s name is placed on a comment line.Modified by Paul Burton <solution@earthlink.net> 12/96 to include new parametersupported by FIGlet and FIGWin.  May also be slightly modified for better useof new full-width/kern/smush alternatives, but default output is NOT changed.';
  $font['a'] = array(
    '      ',
    ' __ _ ',
    '/ _` |',
    '\\__,_|',
    '      ',
  );
  $font['b'] = array(
    ' _    ',
    '| |__ ',
    '| \'_ \\',
    '|_.__/',
    '      ',
  );
  $font['c'] = array(
    '    ',
    ' __ ',
    '/ _|',
    '\\__|',
    '    ',
  );
  $font['d'] = array(
    '    _ ',
    ' __| |',
    '/ _` |',
    '\\__,_|',
    '      ',
  );
  $font['e'] = array(
    '     ',
    ' ___ ',
    '/ -_)',
    '\\___|',
    '     ',
  );
  $font['f'] = array(
    '  __ ',
    ' / _|',
    '|  _|',
    '|_|  ',
    '     ',
  );
  $font['g'] = array(
    '      ',
    ' __ _ ',
    '/ _` |',
    '\\__, |',
    '|___/ ',
  );
  $font['h'] = array(
    ' _    ',
    '| |_  ',
    '| \' \\ ',
    '|_||_|',
    '      ',
  );
  $font['i'] = array(
    ' _ ',
    '(_)',
    '| |',
    '|_|',
    '   ',
  );
  $font['j'] = array(
    '   _ ',
    '  (_)',
    '  | |',
    ' _/ |',
    '|__/ ',
  );
  $font['k'] = array(
    ' _   ',
    '| |__',
    '| / /',
    '|_\\_\\',
    '     ',
  );
  $font['l'] = array(
    ' _ ',
    '| |',
    '| |',
    '|_|',
    '   ',
  );
  $font['m'] = array(
    '       ',
    ' _ __  ',
    '| \'  \\ ',
    '|_|_|_|',
    '       ',
  );
  $font['n'] = array(
    '      ',
    ' _ _  ',
    '| \' \\ ',
    '|_||_|',
    '      ',
  );
  $font['o'] = array(
    '     ',
    ' ___ ',
    '/ _ \\',
    '\\___/',
    '     ',
  );
  $font['p'] = array(
    '      ',
    ' _ __ ',
    '| \'_ \\',
    '| .__/',
    '|_|   ',
  );
  $font['q'] = array(
    '      ',
    ' __ _ ',
    '/ _` |',
    '\\__, |',
    '   |_|',
  );
  $font['r'] = array(
    '     ',
    ' _ _ ',
    '| \'_|',
    '|_|  ',
    '     ',
  );
  $font['s'] = array(
    '    ',
    ' ___',
    '(_-<',
    '/__/',
    '    ',
  );
  $font['t'] = array(
    ' _   ',
    '| |_ ',
    '|  _|',
    ' \\__|',
    '     ',
  );
  $font['u'] = array(
    '      ',
    ' _  _ ',
    '| || |',
    ' \\_,_|',
    '      ',
  );
  $font['v'] = array(
    '     ',
    '__ __',
    '\\ V /',
    ' \\_/ ',
    '     ',
  );
  $font['w'] = array(
    '        ',
    '__ __ __',
    '\\ V  V /',
    ' \\_/\\_/ ',
    '        ',
  );
  $font['x'] = array(
    '     ',
    '__ __',
    '\\ \\ /',
    '/_\\_\\',
    '     ',
  );
  $font['y'] = array(
    '      ',
    ' _  _ ',
    '| || |',
    ' \\_, |',
    ' |__/ ',
  );
  $font['z'] = array(
    '    ',
    ' ___',
    '|_ /',
    '/__|',
    '    ',
  );
  $font['A'] = array(
    '   _   ',
    '  /_\\  ',
    ' / _ \\ ',
    '/_/ \\_\\',
    '       ',
  );
  $font['B'] = array(
    ' ___ ',
    '| _ )',
    '| _ \\',
    '|___/',
    '     ',
  );
  $font['C'] = array(
    '  ___ ',
    ' / __|',
    '| (__ ',
    ' \\___|',
    '      ',
  );
  $font['D'] = array(
    ' ___  ',
    '|   \\ ',
    '| |) |',
    '|___/ ',
    '      ',
  );
  $font['E'] = array(
    ' ___ ',
    '| __|',
    '| _| ',
    '|___|',
    '     ',
  );
  $font['F'] = array(
    ' ___ ',
    '| __|',
    '| _| ',
    '|_|  ',
    '     ',
  );
  $font['G'] = array(
    '  ___ ',
    ' / __|',
    '| (_ |',
    ' \\___|',
    '      ',
  );
  $font['H'] = array(
    ' _  _ ',
    '| || |',
    '| __ |',
    '|_||_|',
    '      ',
  );
  $font['I'] = array(
    ' ___ ',
    '|_ _|',
    ' | | ',
    '|___|',
    '     ',
  );
  $font['J'] = array(
    '    _ ',
    ' _ | |',
    '| || |',
    ' \\__/ ',
    '      ',
  );
  $font['K'] = array(
    ' _  __',
    '| |/ /',
    '| \' < ',
    '|_|\\_\\',
    '      ',
  );
  $font['L'] = array(
    ' _    ',
    '| |   ',
    '| |__ ',
    '|____|',
    '      ',
  );
  $font['M'] = array(
    ' __  __ ',
    '|  \\/  |',
    '| |\\/| |',
    '|_|  |_|',
    '        ',
  );
  $font['N'] = array(
    ' _  _ ',
    '| \\| |',
    '| .` |',
    '|_|\\_|',
    '      ',
  );
  $font['O'] = array(
    '  ___  ',
    ' / _ \\ ',
    '| (_) |',
    ' \\___/ ',
    '       ',
  );
  $font['P'] = array(
    ' ___ ',
    '| _ \\',
    '|  _/',
    '|_|  ',
    '     ',
  );
  $font['Q'] = array(
    '  ___  ',
    ' / _ \\ ',
    '| (_) |',
    ' \\__\\_\\',
    '       ',
  );
  $font['R'] = array(
    ' ___ ',
    '| _ \\',
    '|   /',
    '|_|_\\',
    '     ',
  );
  $font['S'] = array(
    ' ___ ',
    '/ __|',
    '\\__ \\',
    '|___/',
    '     ',
  );
  $font['T'] = array(
    ' _____ ',
    '|_   _|',
    '  | |  ',
    '  |_|  ',
    '       ',
  );
  $font['U'] = array(
    ' _   _ ',
    '| | | |',
    '| |_| |',
    ' \\___/ ',
    '       ',
  );
  $font['V'] = array(
    '__   __',
    '\\ \\ / /',
    ' \\ V / ',
    '  \\_/  ',
    '       ',
  );
  $font['W'] = array(
    '__      __',
    '\\ \\    / /',
    ' \\ \\/\\/ / ',
    '  \\_/\\_/  ',
    '          ',
  );
  $font['X'] = array(
    '__  __',
    '\\ \\/ /',
    ' >  < ',
    '/_/\\_\\',
    '      ',
  );
  $font['Y'] = array(
    '__   __',
    '\\ \\ / /',
    ' \\ V / ',
    '  |_|  ',
    '       ',
  );
  $font['Z'] = array(
    ' ____',
    '|_  /',
    ' / / ',
    '/___|',
    '     ',
  );
  $font['0'] = array(
    '  __  ',
    ' /  \\ ',
    '| () |',
    ' \\__/ ',
    '      ',
  );
  $font['1'] = array(
    ' _ ',
    '/ |',
    '| |',
    '|_|',
    '   ',
  );
  $font['2'] = array(
    ' ___ ',
    '|_  )',
    ' / / ',
    '/___|',
    '     ',
  );
  $font['3'] = array(
    ' ____',
    '|__ /',
    ' |_ \\',
    '|___/',
    '     ',
  );
  $font['4'] = array(
    ' _ _  ',
    '| | | ',
    '|_  _|',
    '  |_| ',
    '      ',
  );
  $font['5'] = array(
    ' ___ ',
    '| __|',
    '|__ \\',
    '|___/',
    '     ',
  );
  $font['6'] = array(
    '  __ ',
    ' / / ',
    '/ _ \\',
    '\\___/',
    '     ',
  );
  $font['7'] = array(
    ' ____ ',
    '|__  |',
    '  / / ',
    ' /_/  ',
    '      ',
  );
  $font['8'] = array(
    ' ___ ',
    '( _ )',
    '/ _ \\',
    '\\___/',
    '     ',
  );
  $font['9'] = array(
    ' ___ ',
    '/ _ \\',
    '\\_, /',
    ' /_/ ',
    '     ',
  );

  return $font;
}
