language: node_js
sudo: false
cache:
  directories:
    - node_modules
env:
  global:
  - SAUCE_USERNAME=flowjs
  - SAUCE_ACCESS_KEY=53e609a9-cb5d-4eac-a888-aa5419836f19
matrix:
  fast_finish: true
  include:
    - env: TEST='unit-tests'
      node_js: "4.2"
    - env: TEST='browser-tests'
      node_js: "4.2"
      addons:
        sauce_connect: true
  allow_failures:
    - env: TEST='browser-tests'
before_install: npm install -g grunt-cli codeclimate-test-reporter
install: npm install
script:
  - $TRAVIS_BUILD_DIR/travis.sh
