<?php

/**
 * Implements hook_permission().
 */
function dru_tickets_permission() {
  return array(
    'view tickets'     => array(
      'title'           => t('View Tickets'),
      'description'     => t('Allow users to view tickets'),
      'restrict access' => TRUE,
    ),
    'create tickets'   => array(
      'title'           => t('Create Tickets'),
      'description'     => t('Allow users to create tickets'),
    ),
    'moderate tickets' => array(
      'title'           => t('Moderate Tickets'),
      'description'     => t('Allow users to moderate tickets'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function dru_tickets_menu() {
  
  $items['admin/content/tickets'] = array(
    'title'            => 'Tickets',
    'description'      => 'Tickets page',
    'page callback'    => 'dru_tickets_page',
    'access arguments' => array('view tickets'),
    'file'             => 'dru_tickets.pages.inc',
  );
  $items['ticket/%node/accept/%'] = array(
    'page callback'    => 'dru_ticket_accept',
    'file'             => 'dru_tickets.pages.inc',
    'page arguments'   => array(1, 3),
    'access arguments' => array('moderate tickets'),
    'type'             => MENU_CALLBACK,
  );
  
  return $items;
}

/**
 * Implements hook_node_info()
 */
function dru_tickets_node_info() {
  return array(
    'ticket' => array(
      'name' => t('Ticket'),
      'base' => 'dru_tickets',
      'description' => t('Claim rules violation or unacceptable behaviour.'),
      'has_title' => FALSE,
    )
  );
}

/**
 * Implement hook_view()
 */
function dru_tickets_view($node, $view_mode, $langcode = NULL) {
  $node->content['test'] = array(
    '#markup' =>  'test',
    '#weight' => 1,
  );
      
  drupal_set_message('<pre>' . print_r($node,true). '</pre>');
  return $node;  
}


/**
 * Implements hook_node_view().
 */
function dru_tickets_node_view($node, $view_mode) {
  
  if ($node->type == 'ticket') {
  
    // Add accept link to tickets
    if (user_access('moderate tickets')) {
      $claim = db_select('ticket_claim', 't')
        ->fields('t')
        ->condition('t.ticket_id', $node->nid, '=')
        ->execute()
        ->fetchObject();
        
      if ($claim->moderate_uid == 0) {
        $token = drupal_get_token('dru_tickets');
        $node->content['links']['comment']['#links']['ticket-accept'] = array(
          'title' => t('Accept'),
          'href' => 'ticket/' . $node->nid . '/accept' . '/' . $token,
          'attributes' => array(
            'class' => array('ticket-accept'),
          ),
        );
      }
    }
  }
}

/**
 * Implements hook_init().
 */
function dru_tickets_init() {
  drupal_add_css(drupal_get_path('module', 'dru_tickets') . '/dru_tickets.css');
}
