<?php

/**
 * Implements hook_install().
 */
function user_filter_notify_install() {
  $message = '@[author:name]:
    
[text:original]


-- Site team [site:name]';
  variable_set('user_info_notify', array(
    'notify' => TRUE,
    'subject' => '@[author:name] mentioned you on [site:name]',
    'message' => $message,
  ));
}

/**
 * Implements hook_uninstall()
 */
function user_filter_notify_uninstall() {
	variable_del('user_info_notify'); 
}