<?php

/**
 * @file
 */

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form().
 */
function dru_forum_form_node_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['taxonomy_forums'])) {
    $langcode = $form['taxonomy_forums']['#language'];
    // DO NOT Make the vocabulary required for 'real' forum-nodes.
    $form['taxonomy_forums'][$langcode]['#required'] = FALSE;
  }
}
