<?php
/**
 * @file
 * Dru_frontpage module.
 */

/**
 * Implements hook_menu().
 */
function dru_frontpage_menu() {
  $items['frontpage'] = array(
    'page callback' => 'dru_frontpage_list',
    'access arguments' => array('access content'),
    'menu_name' => 'navigation',
    'type' => MENU_CALLBACK,
    'title' => 'Front page',
  );
  return $items;
}

/**
 * Implements hook_entity_info_alter().
 */
function dru_frontpage_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['frontpage'] = array(
    'label' => t('Frontpage view'),
    'custom settings' => TRUE,
  );
}


/**
 * Display companies on market place.
 */
function dru_frontpage_list() {
  altpager_items_elements(array(
    5 => 5,
    10 => 10,
    20 => 20,
    40 => 40,
  ));
  
  $query = db_select('node', 'n', array('target' => 'slave'))->extend('AltPager');
 
  if($types = variable_get('frontpage_node_type')){
    $in_types = array();

    foreach($types as $type => $val){
      if($val){
        $in_types[] = $type;
      }
    }
    if(!empty($in_types)){
      $query->condition('n.type', $in_types, 'IN');
    }
  }
  
  $nids = $query
    ->addTag('frontpage_nodes_condition')
    ->fields('n', array('nid', 'created'))
    ->condition('n.status', 1)
    ->condition('n.promote', 1)
    ->orderBy('n.changed', 'DESC')
    ->execute()
    ->fetchCol();
    
  $max = variable_get('frontpage_max_count', 40);
  $current = altpager_count_all_items();
  
  if($current > $max){
    altpager_count_all_items($max);
  }

  if (!empty($nids)) {
    $page['first-pager'] = array(
      '#theme' => 'altpager',
      '#weight' => -10,
    );

    $nodes = node_load_multiple($nids);
    $page += node_view_multiple($nodes, 'frontpage');

    $page['last-pager'] = array(
      '#theme' => 'altpager',
      '#weight' => 10,
    );
    
  }else{
    $default_message = '<p>' . t('No nodes has been promoted yer.') . '</p>';
    $build['default_message'] = array(
      '#markup' => $default_message,
      '#prefix' => '<div id="first-time">',
      '#suffix' => '</div>',
    );
  }
  
  $page['#theme'] = 'frontpage_list';
  return $page;
}
