<?php
/**
 * @file
 */


/**
 * Implements hook_filter_info().
 */
function user_filter_filter_info() {
  $filters = array();
  $filters['user_filter'] = array(
    'title' => t('User filter'),
    'description' => t('View user info by "@username"'),
    'process callback' => 'user_filter_filter_process',
    'cache' => FALSE,
  );
  return $filters;
}

/**
 * Filter process.
 */
function user_filter_filter_process($text, $filter, $format) {
  if (!empty($text)) {
    $text = preg_replace_callback('/(?!\b)((@[\w\d@_-]+)\b)/ui', 'user_filter_callback', $text);
    return $text;
  }
  else {
    return $text;
  }
}

/**
 * Callback user_filter_callback($matches).
 */
function user_filter_callback($matches) {
  $name = drupal_substr($matches[0], 1, $length = NULL);
  $user = user_load_by_name($name);
  if (is_object($user)) {
    return l('@' . $user->name, drupal_get_path_alias('user/' . $user->uid), array('attributes' => array('class' => array('user_filter'), 'data-user' => array($user->name))));
  }
  else {
    return $matches[0];
  }
}
