<?php 

/**
 * Implements hook_filter_info()
 */
function user_filter_filter_info() {
  $filters = array();
  $filters['user_filter'] = array(
    'title' => t('User filter'),
    'description' => t('View user info by "@username"'),
    'process callback' => 'user_filter_filter_process',
    'cache' => FALSE,
  );
  return $filters;
}

/**
 * Filter process
 */
function user_filter_filter_process($text, $filter, $format) {
  if(!empty($text)) {
    $users = user_filter_mention($text);
    if(!empty($users)){
      foreach($users as $user){
        $user_profile = l('@' . $user->name, drupal_get_path_alias('user/' . $user->uid), array('attributes' => array('class' => array('user_filter'), 'data-user' => array($user->name))));
        $text = preg_replace('/@' . $user->name . '/', $user_profile, $text);
      }
    }
    return $text;
  }
  else{
    return $text;
  }
}

/**
 * User Filter API.
 * 
 * Check Users in text by "@username".
 * 
 * Function "user_filter_mention($text)".
 * Return an array with User objects.
 */
function user_filter_mention($text){
  if(!empty($text)) {
    $users = array();
    preg_match_all('/[@][\w\d]+/', $text, $matches);
    foreach($matches[0] as $match){
      $name = drupal_substr($match, 1, $length = NULL);
      $user = user_load_by_name($name);
      if(is_object($user)){
        $users[] = $user;
      }
    }
    return $users;
  }
}