<?php

/**
 * @file
 * Contain main functionality of the module.
 */

/**
 * Constant for variable, which can be used in another modules.
 */
define('RESOLVE_CAN', 'resolve_can');

/**
 * Mark content as resolved.
 */
define('RESOLVE_IS_RESOLVED', 0x01);

/**
 * Mark content as not resolved.
 */
define('RESOLVE_IS_NOT_RESOLVED', 0x00);

/**
 * Implements hook_menu().
 */
function resolve_menu() {
  $items['node/%node/resolve/%comment/%resolve_token'] = array(
    'title' => 'Resolve',
    'page callback' => 'resolve_node_ajax_callback',
    'page arguments' => array(1, 3, 4),
    'access callback' => 'resolve_access',
    'access arguments' => array(1, 3, 4),
    'type' => MENU_CALLBACK,
    'delivery callback' => 'ajax_deliver',
  );
  $items['node/%node/unsolved/%comment/%resolve_token'] = array(
    'title' => 'Unsolved',
    'page callback' => 'resolve_unsolved_node_ajax_callback',
    'page arguments' => array(1, 3, 4),
    'access callback' => 'resolve_access',
    'access arguments' => array(1, 3, 4),
    'type' => MENU_CALLBACK,
    'delivery callback' => 'ajax_deliver',
  );
  return $items;
}

/**
 * Helper function, which performs attaching js files to page.
 */
function resolve_attach_js() {
  static $attached;
  if (!isset($attached)) {
    drupal_add_library('system', 'drupal.ajax');
    drupal_add_js(drupal_get_path('module', 'resolve') . '/resolve.js');
    $attached = TRUE;
  }
}

/**
 * Implements hook_comment_view().
 */
function resolve_comment_view($comment, $view_mode, $langcode) {
  $node = node_load($comment->nid);
  // Attach js files.
  resolve_attach_js();
  $can_resolved = variable_get(RESOLVE_CAN . '_' . $node->type);

  if ($node->resolved_cid == $comment->cid) {
    $comment->best = TRUE;
  }

  $token = resolve_token_to_arg();
  if ($can_resolved && resolve_access($node, $comment, $token)) {
    $links = &$comment->content['links']['comment']['#links'];
    if (!empty($node->resolved_cid) && $node->resolved_cid == $comment->cid) {
      // Add link to comment for resolve the question (node).
      $links['comment-unsolved'] = array(
        'title' => t('Unsolved'),
        'href' => _resolve_unsolved_path($comment->nid, $comment->cid),
        'attributes' => array(
          'class' => array('use-ajax'),
        ),
      );
      $comment->best = TRUE;
    }
    else {
      // Add link to comment for resolve the question (node).
      $links['comment-resolve'] = array(
        'title' => t('resolve'),
        'href' => _resolve_path($comment->nid, $comment->cid),
        'attributes' => array(
          'class' => array('use-ajax'),
        ),
      );
    }
  }
}

/**
 * Performs checking access to resolve a node.
 *
 * @param object $node
 *   Object of checked node.
 *
 * @param mixed $comment
 *   Object or array of comment which is initiator.
 *
 * @param string $token
 *   Object of checked node.
 *
 * @return bool
 *   TRUE if user has access to resolve the node, FALSE otherwise.
 */
function resolve_access($node, $comment, $token) {
  // We can use the function fron several places and
  // the comment can be as array or object of comment.
  $nid = is_object($comment) && isset($comment->nid) ? $comment->nid : NULL;
  if (!$nid && isset($comment['#node']->nid)) {
    $nid = $comment['#node']->nid;
  }
  // Checks that the comment belongs to the node.
  return $nid == $node->nid
    && (user_access('bypass node access') || $GLOBALS['user']->uid == $node->uid)
    && drupal_valid_token($token, 'resolve');
}

/**
 * Implements hook_query_TAG_alter() for node_load_multiple().
 */
function resolve_query_node_load_multiple_alter(QueryAlterableInterface &$query) {
  $query->leftJoin('resolved', 'dr', 'dr.nid = base.nid');
  _resolve_add_fields($query);
}

/**
 * Implements hook_form_FORM_ID_alter() for node_type_form().
 */
function resolve_form_node_type_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['type']) && module_exists('comment')) {
    $type = $form['#node_type']->type;
    $form['comment'][RESOLVE_CAN] = array(
      '#type' => 'checkbox',
      '#title' => t('The questions can be resolved by comments.'),
      '#description' => t('Any node of the content type can be resolved by a comment.'),
      '#default_value' => variable_get(RESOLVE_CAN . '_' . $type),
    );
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function resolve_preprocess_comment(&$variables) {
  if (!empty($variables['elements']['#comment']->best)) {
    $variables['classes_array'][] = 'best-comment';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function resolve_preprocess_node(&$variables) {
  $is_resolved = !empty($variables['resolved']);
  $correct_mode = $variables['view_mode'] == 'full';

  // Adding best comment to bottom of the node.
  if ($correct_mode && $is_resolved && isset($variables['content'])) {
    $content = &$variables['content'];

    if ($comment = comment_load($variables['resolved_cid'])) {
      $variables['has_resolved_comment'] = TRUE;
      $content['resolved_comment'] = comment_view($comment, $variables['node']);

      // Get max weight of the page.
      $weight = 0;
      foreach ($content as $item) {
        if (isset($item['#weight']) && $item['#weight'] > $weight) {
          $weight = $item['#weight'];
        }
      }

      // If weight not found.
      if ($weight < count($content)) {
        $weight = count($content) + 1;
      }

      $content['resolved_comment']['#weight'] = ++$weight;
    }
  }
}

/**
 * Ajax callback for mark a node as resolved.
 *
 * @param object $node
 *   Object of a node.
 *
 * @return array
 */
function resolve_node_ajax_callback($node, $comment, $token) {
  $commands = array();
  $keys = array();
  $record = array(
    'nid' => $node->nid,
    'cid' => $comment->cid,
    'resolved' => TRUE,
  );

  // If the node has mark resolved, then we should just update his.
  if (isset($node->resolved)) {
    $keys[] = 'nid';
  }
  drupal_write_record('resolved', $record, $keys);
  resolve_update_page_state($node, $commands);
  $commands[] = resolve_ajax_command_resolve();
  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}

/**
 * Ajax callback for mark a node as resolved.
 *
 * @param object $node
 *   Object of a node.
 *
 * @return array
 */
function resolve_unsolved_node_ajax_callback($node, $comment, $token) {
  $commands = array();
  $transaction = db_transaction(__FUNCTION__);
  try {
    db_delete('resolved')
      ->condition('nid', $node->nid)
      ->condition('cid', $comment->cid)
      ->execute();
  }
  catch (Exception $e) {
    $transaction->rollback();
    watchdog_exception('resolve', $e, 'The comment can not be unsolved.', array(), WATCHDOG_ERROR);
  }
  resolve_update_page_state($node, $commands);
  $commands[] = resolve_ajax_command_unsolved();
  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}

/**
 * Performs tasks after resolve question (node).
 *
 * @param object $node
 *   Node which should be rendered as page.
 *
 * @param array $commands
 *   List of commands witch should be updated.
 */
function resolve_update_page_state($node, &$commands) {
  $node = node_load($node->nid, NULL, TRUE);
  $node_view = node_view($node);
  $commands[] = ajax_command_replace('#node-' . $node->nid, drupal_render($node_view));
}

/**
 * Performs resolve a node.
 */
function resolve_ajax_command_resolve() {
  return array(
    'command' => 'resolve',
  );
}

/**
 * Performs resolve a node.
 */
function resolve_ajax_command_unsolved() {
  return array(
    'command' => 'unsolved',
  );
}

/**
 * Allows to protect the action from CSRF vulnerabilities.
 *
 * @return string
 *   Generate token for "resolve" action.
 */
function resolve_token_to_arg() {
  $token = &drupal_static(__FUNCTION__);
  if (!isset($token)) {
    $token = drupal_get_token('resolve');
  }
  return $token;
}

/**
 * Add mark that node is resolved in title of node/page.
 *
 * @param string $title
 *   Some title of node or page.
 * @param bool $resolved
 *   If set to TRUE, then the flag says: "Hey, the node is resolved!".
 */
function resolve_add_mark($node, $resolved) {
  return theme('resolved', array(
    'context' => $node,
  ));
}

/**
 * Adds fields from table "resolved" to loaded object of node(s).
 */
function _resolve_add_fields(QueryAlterableInterface &$query) {
  $query->addField('dr', 'resolved');
  $query->addField('dr', 'cid', 'resolved_cid');
}

/**
 * Helper for generate page to resolve a node.
 *
 * @param int $nid
 *   Node ID.
 * @param int $cid
 *   Comment ID.
 *
 * @return string
 *   Path to resolve the node, which will be received by nid.
 */
function _resolve_path($nid, $cid) {
  return 'node/' . $nid . '/resolve/' . $cid . '/' . resolve_token_to_arg();
}

/**
 * Helper for generate page to unsolve a node.
 *
 * @param int $nid
 *   Node ID.
 * @param int $cid
 *   Comment ID.
 *
 * @return string
 *   Path to resolve the node, which will be received by nid.
 */
function _resolve_unsolved_path($nid, $cid) {
  return 'node/' . $nid . '/unsolved/' . $cid . '/' . resolve_token_to_arg();
}

/**
 * Implements hook_theme().
 */
function resolve_theme($existing, $type, $theme, $path) {
  return array(
    'resolved' => array(
      'variables' => array(
        'resolved' => RESOLVE_IS_RESOLVED,
      ),
    ),
  );
}

/**
 * Returns HTML for a marker for resolved content.
 *
 * @param $variables
 *   An associative array containing:
 *   - type: Number representing the marker type to display.
 *     See RESOLVE_IS_RESOLVED, RESOLVE_IS_NOT_RESOLVED.
 */
function theme_resolved($variables) {
  return $variables['resolved'] == RESOLVE_IS_RESOLVED ? '[' . t('Resolved') . '] ' : '';
}

/**
 *
 */
function resolved_node_can_be_resolved($node) {
  return isset($node->type) ? variable_get(RESOLVE_CAN . '_' . $node->type) : FALSE;
}
