<?php
/**
 * @file
 * Marketplacd module.
 */


/**
 * Implements hook_node_info()
 */
function marketplace_node_info() {
    return array(
        'organization' => array(
            'name' => t('Organization'),
            'base' => 'organization',
            'description' => t('Create organization page'),
            'has_title' => TRUE,
            'title_label' => t('Organization name')
         )
    );
}

/**
 * Implement hook_form()
 */
function marketplace_form($node, $form_state) {
  $form =  node_content_form($node, $form_state);
  $type = node_type_get_type($node);
  drupal_set_message('<pre>' . print_r($type, TRUE) . '</pre>');
  drupal_set_message('<pre>' . print_r($form, TRUE) . '</pre>');
  return $form;
}