<?php

/**
 * Implements of hook_menu().
 */
function user_filter_popup_menu() {
  $items['user/info/ajax/%'] = array(
    'page callback' => 'user_filter_popup_info',
    'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access user profiles'),
    'delivery callback' => 'user_filter_popup_ajax_callback',
    'file' => 'user_filter_popup.page.inc',
  );
  return $items;
}

/**
 * Implements hook_entity_info_alter()
 */
function user_filter_popup_entity_info_alter(&$entity_info){
  $entity_info['user']['view modes']['user_info'] = array(
    'label' => t('User Info'),
    'custom settings' => TRUE,
  );
}

/**
 * Callback for view user tip
 */
function user_filter_popup_ajax_callback($profile){
  global $user;
  $content = drupal_render($profile);
  print $content;
  drupal_page_footer();
}

/**
 * Implements hook_init()
 * Add css and js files
 */
function user_filter_popup_init() {
  drupal_add_css(drupal_get_path('module', 'user_filter_popup') . '/user_filter_popup.css');
  drupal_add_js(drupal_get_path('module', 'user_filter_popup') . '/js/user_filter_popup.js');
}

function user_filter_popup_preprocess_user_profile(&$vars){
  if ($vars['elements']['#view_mode'] == 'user_info') {
    $vars['theme_hook_suggestions'][] = 'user_profile__user_info';
    //dpm($vars);
  }
}