<?php 

/**
 * Implements hook_validator_info().
 */
function antiswearing_validate_validator_info(){
  $items = array();
  $items[] = array(
    'type' => 'text',
    'title' => 'Мат-фильтр',
    'description' => 'Запрет употребления матершинных слов',
    'name' => 'mat',
    'callback' => 'mat_callback',
  );
  return $items;
}

/**
 * Validator callback. Use PHP-class "php-obscene-censor-rus"
 * by Vearutop: https://github.com/vearutop/php-obscene-censor-rus
 */
function mat_callback($field, $field_name, $entity, &$message){
  module_load_include('php', 'antiswearing_validate', 'obscene/obscene.class');
  
  $values = array();
  $valid = array();
  if($field_name == 'title'){
    $values[] = $field;
    $label = t('Title');
  }
  else{
    $info = field_info_instance('node', $field_name, $entity->type);
    $label = $info['label'];
    if(!empty($field['und'])){
      foreach($field['und'] as $field_value){
        $values[] = $field_value['value'];
      }
    }
  }
  
  foreach($values as $value){
    if(ObsceneCensorRus::filterText($value)){
      $valid[] = FALSE;
    }
  }
  
  if(in_array(FALSE, $valid)){
    $message = t('Field "@field" isn\'t valid! Use profanity is prohibited!', array('@field' => $label));
    return FALSE;
  }
  else{
    return TRUE;
  }
}